title: thegeorgejr!
email: georgekuriakosejr@gmail.com
description: "I am a web-desiginer who loves to create experiences which stand out. I have a passion for making and trying something different everytime to feed my curiosity. "
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://thegeorgejr.com"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - .sass-cache/
  - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
